In [10]:
%cd ..
from API import *
from itertools import product
from pprint import pprint
from progressbar import ProgressBar
from tqdm.notebook import tqdm

import numpy as np
from IPython.display import display


e:\REMOTE\YandexDisk\MPEI\DIP\part 2


# Генерация входной и выходной базы данных
### Входные параметры


|Наименование                               |Обозначение    |Переменная |Размерность|
|---------------------------------------------------------------|---------------|-----------|-----------|
|Статическое давление на входе в ступень                        |$p_0$          |p_0        |МПа        |
|Статическая температура на входе в ступент                     |$t_0$          |t_0        |degC       |
|Статический теплоперепад ступени                               |$H_0$          |H_0        |кДж/кг     |
|Степень реактивности на среднем диаметре                       |$\rho$         |reaction   |-          |
|Диаметр корня ступени                                          |$d_{к}$        |d_hub      |м          |
|Абсолютный угол выхода потока из соплвой решетки ступени       |$\alpha_{1}$   |alpha_1    |deg        |
|Массовый расход                                                |$G_0$          |G_0        |кг/с       |

Диапазоны вариации входных параметров:

In [11]:
# input_paramaters_dict = {
#     "p_0":      [2, 9, 1],
             
#     "t_0":      [300, 550, 50],
    
#     "H_0":      [20, 160, 20],
    
#     "reaction": [0.1, 0.6, 0.05],
    
#     "d_hub":    [0.65, 1.0, 0.05],
    
#     "n":        [50, 101, 50],
    
#     "alpha_1":  [9, 30, 2],
    
#     "G_0":      [20, 180, 40]
# }
input_paramaters_dict = {
    "p_0":      [6, 8, 1],
             
    "t_0":      [300, 400, 50],
    
    "H_0":      [20, 60, 20],
    
    "reaction": [0.1, 0.3, 0.05],
    
    "d_hub":    [0.65, 1.0, 0.1],
    
    "n":        [50, 101, 50],
    
    "alpha_1":  [9, 15, 2],
    
    "G_0":      [20, 180, 40]
}

In [12]:
input_parameters_arange = [np.arange(*input_paramaters_dict[param]) for param in input_paramaters_dict]
input_parameters_arange

[array([6, 7]),
 array([300, 350]),
 array([20, 40]),
 array([0.1 , 0.15, 0.2 , 0.25]),
 array([0.65, 0.75, 0.85, 0.95]),
 array([ 50, 100]),
 array([ 9, 11, 13]),
 array([ 20,  60, 100, 140])]

Общее число итераций

In [13]:
number_of_rows = len(list(product(*input_parameters_arange)))
number_of_rows

3072

### Выходные параметры

|Наименование                                                   |Обозначение    |Переменная |Размерность|
|---------------------------------------------------------------|---------------|-----------|-----------|
|Успешность расчета ступени                                     |$isOK$         |isOK       |-          |               
|Относительный лопаточный КПД                                   |$p_0$          |p_0        |МПа        |
|Лопаточная мощность ступени                                    |$t_0$          |t_0        |degC       |
|Длина лопатки                                                  |$H_0$          |H_0        |кДж/кг     |


### Генерация датасета

In [14]:
# Data arrays
save_input_parameters_list = [np.full(number_of_rows,None, dtype=float) for param in input_paramaters_dict]
save_input_parameters_list

[array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan])]

In [15]:
output_parameters_names_list = [
    'isOK',
    'eff_ol',
    'Nu',
    'l_1',
]
save_output_parameters_list = [np.full(number_of_rows,None, dtype=float) for param in output_parameters_names_list]
save_output_parameters_list

[array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan]),
 array([nan, nan, nan, ..., nan, nan, nan])]

```python
def get_results(self):
    return {
        'd':        ...,
        'l_1':      ...,
        'l_2':      ...,
        'c_0':      ...,
        'c_1':      ..., 
        'c_2':      ...,
        'w_1':      ...,
        'w_2':      ...,
        'alpha_0':  ...,
        'alpha_1':  ...,
        'beta_1':   ...,
        'beta_2':   ...,
        'u':        ...,
        'X':        ...,
        'Delta_Hs': ...,
        'Delta_Hr': ...,
        'phi':      ...,
        'psi':      ...,
        'eff_ol':   ...,
        'E_0':      ...,
        'b_1':      ...,
        'b_2':      ...,
        'Name_1':   ...,
        'Name_2':   ...,
        'Nu':       ...
    }
```

In [16]:


# # Создаем текстовый виджет для вывода значения переменной
# output_widget = widgets.Output()

# # Определяем переменную, которую нужно мониторить
# a = 0

# # Функция, которая будет вызываться для обновления значения переменной
# def update_a():
#     global a
#     a += 1
#     # Очищаем предыдущий вывод и выводим новое значение переменной
#     with output_widget:
#         # Очищаем предыдущий вывод
#         output_widget.clear_output(wait=True)
#         # Выводим новое значение переменной
#         print("Значение переменной a:", a)

# # Создаем кнопку, которая будет вызывать функцию update_a при нажатии
# button = widgets.Button(description="Обновить a")
# button.on_click(lambda _: update_a())

# # Отображаем кнопку и текстовый виджет в ячейке
# display(button)
# display(output_widget)

In [17]:
from time import sleep
import ipywidgets as widgets
from IPython.display import display

widgets_list = []
widgets_text_list = [
    'p_0 = \t\t{} MPa',
    't_0 = \t\t{} degC',
    'H_0 = \t\t{} kJ/kg',
    "reaction = \t{}",
    "d_hub = \t{} m",
    "n = \t\t{} 1/s",
    "alpha_1 = \t{} deg",
    "G_0 = \t\t{} kg/s"
]



for param in input_paramaters_dict:
    widgets_list.append(widgets.Output())
print(len(widgets_list))

def set_widgets_value(inlist):
    for index, wid in enumerate(widgets_list):
        with wid:
            wid.clear_output(wait=True)
            print(widgets_text_list[index].format(inlist[index]))

set_widgets_value([0,0,3,4,6,8,9,0,10,1])

def print_wid():
    for wid in widgets_list:
        display(wid)




8


In [18]:
itaration:int = 0


print_wid()
with tqdm(total = number_of_rows, desc = 'Processing') as pbar:
    for p_i, t_i, H_i, reaction_i, d_hub_i, n_i, alpha_1_i, G_0_i in tqdm(product(*input_parameters_arange)):
        stage = Stage(
            # main iterable parameters
            p_0 = p_i,
            t_0 = t_i,
            G_0 = G_0_i,
            d_hub = d_hub_i,
            n = n_i,
            reaction = reaction_i,
            alpha_1eef = alpha_1_i,
            H_0 = H_i,

            # other
            c_0 = np.sqrt(2000 * 0.05 * H_i),
            alpha_0 = 90,
            Delta_pr = 0.003,
        )

        # Save input parameters
        save_input_parameters_list[0][itaration] = p_i
        save_input_parameters_list[1][itaration] = t_i
        save_input_parameters_list[2][itaration] = H_i
        save_input_parameters_list[3][itaration] = reaction_i
        save_input_parameters_list[4][itaration] = d_hub_i
        save_input_parameters_list[5][itaration] = n_i
        save_input_parameters_list[6][itaration] = alpha_1_i
        save_input_parameters_list[7][itaration] = G_0_i

        set_widgets_value([
            p_i, 
            t_i,
            H_i,
            reaction_i,
            d_hub_i,
            n_i,
            alpha_1_i,
            G_0_i])
        
        
        # Save output parameters
        save_output_parameters_list[0][itaration] = stage.isOK()
        save_output_parameters_list[1][itaration] = stage.get_results()['eff_ol']
        save_output_parameters_list[2][itaration] = stage.get_results()['Nu']
        save_output_parameters_list[3][itaration] = stage.get_results()['l_1']

        itaration += 1
        pbar.update(1)
        pbar.set_description(f"PROGRESS")
        


# pbar.finish()

Output(outputs=({'name': 'stdout', 'text': 'p_0 = \t\t0 MPa\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 't_0 = \t\t0 degC\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'H_0 = \t\t3 kJ/kg\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'reaction = \t4\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'd_hub = \t6 m\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'n = \t\t8 1/s\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'alpha_1 = \t9 deg\n', 'output_type': 'stream'},))

Output(outputs=({'name': 'stdout', 'text': 'G_0 = \t\t0 kg/s\n', 'output_type': 'stream'},))

Processing:   0%|          | 0/3072 [00:00<?, ?it/s]

0it [00:00, ?it/s]

KeyboardInterrupt: 